#! it's useful to be able to organize separate components
#! into libraries. you can clone them into _ytt_lib directory
#! and load them as shown below. 

#! any files inside library's own _ytt_lib location
#! is not accessbile to library consumers, hence making
#! it possible to keep chosen functionality private to the library.

#@ load("@github.com/k14s/test-lib:funcs.star", "testfunc")

result: #@ testfunc()
