#! example is based on the following post: https://bit.ly/2QNCWab
#! we start by creating a simple pod+service configuration.
#! take a look and move to next example: k8s-ingress-with-defs

#@ load("@ytt:data", "data")

#@ def/end labels():
app: apple

kind: Pod
apiVersion: v1
metadata:
  name: apple-app
  labels: #@ labels()
spec:
  containers:
  - name: apple-app
    image: hashicorp/http-echo
    args:
    - #@ "-listen=:" + str(data.values.port)
    - #@ "-text=" + data.values.text
---
kind: Service
apiVersion: v1
metadata:
  name: apple-service
spec:
  selector: #@ labels()
  ports:
  - port: #@ data.values.port
