#! some variables need to be configurable externally
#! we can specify them in a separate file or a separate
#! YAML document node

#@ load("@ytt:data", "data")

list_with_a_map: #@ data.values.my_map
