#! it's useful sometimes to split data values
#! into multiple files and have them be combined
#! before templating happens, for example,
#! for splitting default and production values

#@ load("@ytt:data", "data")

data: #@ data.values.keys
domains: #@ data.values.names
