name: test-windows
on: 
  push:
  pull_request:
    types: [opened, reopened]
jobs:
  test-windows:
    name: Test Windows
    runs-on: windows-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v1
      with:
        go-version: "1.13"
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run Tests
      shell: powershell
      run: |
        .\hack\test-windows.ps1
